### ISSUE TITLE
Adjusting the waterfall speed to lower than 1

### ISSUE THREAD

**Issue by ZapdoZ** [pachacamac/spectrum_analyzer#2]
Apparently You can set the waterfall speed by adjusting the var moveBy.
However, if I set it to anything lower than 1, the things that are drawn begin to weirdly fade out by getting more blurred overtime.
Is there any bypass to this?
![1](https://user-images.githubusercontent.com/61920010/81744666-cb52c200-94a3-11ea-938e-a1d0094011f7.jpg)
![2](https://user-images.githubusercontent.com/61920010/81744669-cc83ef00-94a3-11ea-9592-c59b10620f5b.jpg)

**Comment by pachacamac** [comment]
What are you trying to accomplish by this? `moveBy` basically defines how many pixels to move the waterfall per time unit...

**Comment by ZapdoZ** [comment]
Yeah, that's exactly what I'm trying to accomplish in order to fit a longer period of audio stream onto one area of the waterfall -> basically slowing it down. Is there another possibility to slow it down without changing moveBy?

**Comment by pachacamac** [comment]
So the draw function tries to get called as often as possible by using requestAnimationFrame to schedule itself. You could set a fixed framerate (see e.g. https://riptutorial.com/html5-canvas/example/18718/set-frame-rate-using-requestanimationframe) to slow this down. You could also keep everything as is but average the values in a bucket. Basically have second frequencies array (say frequenciesAvg) of the same length as frequencies. Then just add frequencies[i] to frequenciesAvg[i] for a N frames and then afterwards divide frequencies[i] by N. Then draw frequenciesAvg instead of frequencies. N then controls the speed so to say.

**Comment by ZapdoZ** [comment]
Apologies for the late reply.
Since I'm not experienced with javascript at all, would you mind telling me how to implement one of the solutions to your code in particular?

**Comment by pachacamac** [comment]
Hey I created you a new branch with the discussed changes. I implemented the buffer approach. Check it out here: https://github.com/pachacamac/spectrum_analyzer/blob/buffered/waterfall.js#L66-L84

**Comment by ZapdoZ** [comment]
Thank you! That works perfectly!
